# version: "3.9"
services:
  frontend:
    platform: linux/amd64
    build: .
    ports:
      - "5002:80"
    volumes:
      - tooling_frontend:/var/www/html
    depends_on:
     - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: toolingdb
      MYSQL_USER: genet
      MYSQL_PASSWORD: Admin1234
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
volumes:
  tooling_frontend:
  db: